stages:
  - build
  - deploy

variables:
  GHCR_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  KUBE_NAMESPACE: default

build:
  stage: build
  script:
    - docker build -t $GHCR_IMAGE .
    - echo $GHCR_PASSWORD | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
    - docker push $GHCR_IMAGE

staging_deploy:
  stage: deploy
  environment:
    name: staging
  script:
    - kubectl set image deployment/webhook-listener webhook-listener=$GHCR_IMAGE -n $KUBE_NAMESPACE
    - kubectl rollout status deployment/webhook-listener -n $KUBE_NAMESPACE
  only:
    - staging

production_deploy:
  stage: deploy
  environment:
    name: production
  script:
    - kubectl set image deployment/webhook-listener webhook-listener=$GHCR_IMAGE -n $KUBE_NAMESPACE
    - kubectl rollout status deployment/webhook-listener -n $KUBE_NAMESPACE
  only:
    - main

rollback:
  stage: deploy
  environment:
    name: production
  when: manual
  script:
    - kubectl rollout undo deployment/webhook-listener -n $KUBE_NAMESPACE
  only:
    - main
