apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-listener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhook-listener
  template:
    metadata:
      labels:
        app: webhook-listener
    spec:
      containers:
      - name: webhook-listener
        image: webhook-listener:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: '500m'
            memory: '512Mi'
          requests:
            cpu: '200m'
            memory: '256Mi'
        env:
          - name: NODE_ENV
            value: production
