```yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/zlr-sashrika/webhook-listener:${{ github.sha }} .
        docker push ghcr.io/zlr-sashrika/webhook-listener:${{ github.sha }}
    - name: Deploy to Kubernetes
      uses: k8s-deploy@v1
      with:
        manifest-path: ./k8s
        secrets: ${{ secrets.K8S_SECRET }}
        images: |
          ghcr.io/zlr-sashrika/webhook-listener:${{ github.sha }}
```